# Generated by Django 4.2.24 on 2025-10-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0003_studentdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='admindetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminfullname', models.CharField(max_length=30)),
                ('adminemail', models.EmailField(max_length=30)),
                ('adminusername', models.CharField(max_length=20)),
                ('adminpassword', models.CharField(max_length=16)),
            ],
        ),
    ]
