# Generated by Django 4.2.24 on 2025-10-25 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0008_coursevideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched', models.BooleanField(default=False)),
                ('watched_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.userdetails')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.coursevideo')),
            ],
            options={
                'unique_together': {('student', 'video')},
            },
        ),
    ]
